"""
Mapping of NOAA Weather Radio SAME event codes to human-readable names.
Pure data module.
"""

SAME_EVENT_CODES: dict[str, str] = {
    # Critical Events
    "TOR": "Tornado Warning",
    "SVR": "Severe Thunderstorm Warning",
    "FFW": "Flash Flood Warning",
    "FFE": "Flash Flood Emergency",
    "FLW": "Flood Warning",
    "SMW": "Special Marine Warning",
    "HWW": "High Wind Warning",
    "BZW": "Blizzard Warning",
    "WSW": "Winter Storm Warning",
    "ICE": "Ice Storm Warning",
    "EWW": "Extreme Wind Warning",
    "DSW": "Dust Storm Warning",
    "AVW": "Avalanche Warning",
    "EAN": "Emergency Action Notification",
    "NIC": "National Information Center",
    "TOA": "Tornado Watch",
    "SVA": "Severe Thunderstorm Watch",
    "FFA": "Flash Flood Watch",
    "FLA": "Flood Watch",
    "WSA": "Winter Storm Watch",
    "HWA": "High Wind Watch",
    "DGL": "Downgrade",
    "FRW": "Fire Warning",
    "FRA": "Fire Watch",
    "WND": "High Wind Advisory",
    "FFS": "Flash Flood Statement",
    "FLS": "Flood Statement",
    "SVS": "Severe Weather Statement",
    "SPS": "Special Weather Statement",
    "RWT": "Required Weekly Test",
    "RMT": "Required Monthly Test",
    "DMO": "Practice/Demo Warning",
    "ADR": "Administrative Message",
    "CAE": "Child Abduction Emergency",
    "CDW": "Civil Danger Warning",
    "CEM": "Civil Emergency Message",
    "CFW": "Coastal Flood Warning",
    "EVI": "Evacuation Immediate",
    "HMW": "Hazardous Materials Warning",
    "LEW": "Law Enforcement Warning",
    "LAE": "Local Area Emergency",
    "NUW": "Nuclear Power Plant Warning",
    "RHW": "Radiological Hazard Warning",
    "SPW": "Shelter in Place Warning",
    "VOW": "Volcano Warning",
    "TSA": "Tsunami Watch",
    "TSW": "Tsunami Warning",
}
